# Generated by Django 3.1.3 on 2020-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TtsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.IntegerField()),
                ('day_part', models.IntegerField()),
                ('first_seen_local', models.IntegerField()),
                ('first_seen_utc', models.IntegerField()),
                ('misc_id', models.IntegerField()),
                ('location', models.IntegerField()),
                ('model_id', models.IntegerField()),
                ('total_time_to_service', models.IntegerField()),
            ],
        ),
    ]
